### ISSUE TITLE
Svelte v5 support?

### ISSUE THREAD

**Issue by webJose** [orefalo/svelte-splitpanes#106]
Plans on supporting the new Svelte?

**Comment by orefalo** [comment]
Eventually, yes, it's on my to-do list. 

I just lack the motivation at the moment because I am working on a tree component. I have marked many tickets as enhancements, and those will probably make it after triage, support for both px and % is something I really want ot implement.

So no date,
Feel free to chip in...;-)

**Comment by orefalo** [comment]
Initiative welcomed,
The component works perfectly with svelte 5 as it is. Not surprising, the migration tool works as well
`sv migrate svelte5 .`

I was considering addressing the functional gaps in this new svelte5 - but I don't have time right now.

**Comment by bcspragu** [comment]
> The component works perfectly with svelte 5 as it is.

Can confirm, I just changed the `peerDependencies` to include `"svelte": "^5.0.0"` and it appears to work with zero other changes in my Svelte 5 app.

Perhaps that's enough of a change for now, just updating the peerDependencies so people on Svelte 5 can use your (awesome) library without `npm i --force`?

**Comment by orefalo** [comment]
oh, interesting... 
but then... this will force an upgrade to svelte 5, right?

How would I tell npm to support v4 & v5?

**Comment by orefalo** [comment]
found it

"dependency-name": "1.0.0 || 2.0.0"

**Comment by orefalo** [comment]
v8.0.9 release - give it a few minutes to reach npm

**Comment by bcspragu** [comment]
> v8.0.9 released - give it a few minutes to reach npm

Works great, thanks!

**Comment by digitalit** [comment]
Hi guys,

I really would like to use this in my Svelte 5 project but i can't figure out how to. 

@bcspragu did you convert this package to use Svelte 5 / runes?

Have a nice day
/Peter Sweden

**Comment by orefalo** [comment]
I did, it supports both 4 & 5

**Comment by digitalit** [comment]
> I did, it supports both 4 & 5

oh, maybe i did something wrong when i installed it cause its old state declarations everywhere.

Is there any special install command like npm install xxxx@next ?

Just by adding in split.svelte file:
`import { Pane, Splitpanes } from 'svelte-splitpanes';`

I get:

` ERROR: [plugin: vite-plugin-svelte:optimize-svelte] node_modules/svelte-splitpanes/dist/Pane.svelte:9:0 Cannot use `export let` in runes mode — use `$props()` instead
`

Please advise :)

**Comment by orefalo** [comment]
Good Morning,

You are likely in Svelte 5 strict mode. Splitpanes has not been rewritten for Rhunes, as this would require maintaining two separate versions. Instead, it has been made compatible.

For this to work, you need to ensure your project is not in strict mode:

Please check your top level **svelte.config.js** , ensure this section is not there

```
export default {
  compilerOptions: {
    runes: true
  }
};
```

or check that your component does not have a 
`<svelte:options runes={true} />`

I am not planning to rewrite the component to svelte 5, but could gladly take a pull req.

Hope this helps,
Olivier

PS: I don't recall maintaining a @next tag in npm, install instructions are well documented.

**Comment by digitalit** [comment]
Tank you @orefalo ,

I'm sure your documentation is well documented. I apologize for not being skilled enough to determine the npm tags.

Anyway, comment out:

`	preprocess: vitePreprocess(),
	/*compilerOptions: {
		runes: true
	},*/`
in svelte.config.js made it work.

Just that since i'm not that skilled i thought setting runes to strict would prevent me from accidentally write legacy code.

I would be great i i could keep runes true and just override/exclude node_modules/svelte-splitpanes so everything is strikt runes but svelte-splitpanes.

Is this possible?

Have a nice day

**Comment by orefalo** [comment]
You raise a valid point; I will clarify the above points in the documentation to assist newcomers.

Certainly, it's straightforward.
You can manage rune mode strictness using <svelte:options runes={true} /> directly in your component.

Hope this helps,

**Comment by orefalo** [comment]
closing this ticket - work in completed.
